[out:json][timeout:200];
(
area["ISO3166-1"="CD"][admin_level=2];
n["man_made"="antenna"](area)(-2.05,27,3.8,31.1);
area["ISO3166-1"="CD"][admin_level=2];
n["tower:type"="communication"](area)(-2.05,27,3.8,31.1);
area["ISO3166-1"="CD"][admin_level=2];
n["man_made"="mast"](area)(-2.05,27,3.8,31.1);
area["ISO3166-1"="CD"][admin_level=2];
n["man_made"="communications_tower"](area)(-2.05,27,3.8,31.1);
);
out body;
>;
out body;
